# Generated by Django 5.1.6 on 2025-06-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0002_song_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='date_added',
        ),
    ]
