# Generated by Django 5.1.6 on 2025-06-28 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0004_song_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
