# Generated by Django 5.1.6 on 2025-07-20 07:11

from django.db import migrations, models
from datetime import datetime,timedelta

class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0007_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=timedelta(seconds=0)),            
            preserve_default=False,
        ),
    ]
