# Generated by Django 5.1.6 on 2025-07-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0010_alter_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='web_album',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
